color0 #162127
color1 #fd4663
color2 #67c8e4
color3 #5c7ed6
color4 #7d66cc
color5 #93d8ec
color6 #96ade9
color7 #f2f3f3
color8 #5c6d71
color9 #fd4663
color10 #67c8e4
color11 #5c7ed6
color12 #7d66cc
color13 #93d8ec
color14 #96ade9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #162127
background            #162127
foreground            #f2f3f3
selection_foreground  #afb5b6
selection_background  #1d2c34
active_border_color   #67c8e4
inactive_border_color #1d2c34
url_color             #67c8e4

active_tab_foreground   #182225
active_tab_background   #67c8e4
inactive_tab_foreground #afb5b6
inactive_tab_background #1d2c34
cursor_trail_color      #afb5b6
